### ISSUE TITLE
Per feed "dontUseProxy" option is broken

### ISSUE THREAD

**Issue by Leiaz** [lwindolf/liferea#383]
In Liferea from git master branch, on ArchLinux with libsoup 2.54.1, using the option doesn't prevent the manually set or environment set proxy from being used.

This may be due the fact that `soup_proxy_uri_resolver_get_type` is deprecated (used with `soup_message_disable_feature`).

**Comment by lwindolf** [comment]
Me hates GNOME style deprecations... :-)

**Comment by Leiaz** [comment]
By the way `soup_session_async_new_with_options` is deprecated too :D  But even if it returns a plain SoupSession, according to this : [Porting to the new SoupSession](https://developer.gnome.org/libsoup/stable/libsoup-session-porting.html) I think it should behaves the same way. :)

**Comment by lwindolf** [comment]
@Leiaz Just that I don't mistakenly close this: is this fixed by #382 ?

**Comment by Leiaz** [comment]
No it is not fixed. I don't see a way to change the proxy just for a specific SoupMessage. Only way I can think of is sending it with a different "no proxy" SoupSession.

**Comment by lwindolf** [comment]
Thank you for the thougths. I remember having a working multi-session code previously to easily switch to any of the possible proxy variants...

**Comment by lwindolf** [comment]
Hope this solves it.

**Comment by Leiaz** [comment]
Almost. The default for SoupSession is to use the system defined proxy, to really use no proxy either proxy-resolver or proxy-uri has to be set to NULL (setting one automatically unsets the other).

And I think  you can remove the `async` from `soup_session_async_new_with_options`. SoupSessionAsync and SoupSessionSync are deprecated, using `soup_session_queue_message` sends the message asynchronously.

**Comment by lwindolf** [comment]
Thank you for the hints. Should be fixed now.
