### ISSUE TITLE
When resuming from sleep, Liferea attempts to fetch feeds before wifi has a chance to connect.

### ISSUE THREAD

**Issue by ghost** [lwindolf/liferea#558]
When the computer is turned back on from sleep state, Liferea attempts to fetch feed updates right away, before wifi has a chance to establish a connection which results in several feeds not updating and displaying an error until either the feeds are manually updated or the next scheduled update occurs.

**Comment by lwindolf** [comment]
That's not an easy problem to solve. While Liferea registers with DBUS to receive network monitoring events to know if wifi is offline or not, this doesn't work well with suspend. The thing is when you suspend the Wifi was online and once you wake up the network manager needs some time until it decides it is offline and only then emits an offline event Liferea can handle. But of course updates will happen immediately after a longer suspend as Liferea each minute checks which feeds need updating.

So after e.g. 12h suspend with update interval set to 1h on wakeup all feeds have to be updated immediately and all will fail...

I think we need to to detect the network down situation internally too. So the network monitor would be able to handle the following states

- surely down (because reported by network-manager)
- probably online
- probably offline because of corresponding errors on recent fetches

In this scenario the worst case would be to get stuck in "probably offline" due to misinterpreted feed fetch errors. I'm not sure if it is worth the effort.

**Comment by lwindolf** [comment]
Or maybe time lapse detection and a short back-off period (1-2min) for the Wifi to decide if it is online or offline would be safer. Time lapse is easy to detect and could be an additional condition in network_monitor_is_online()

**Comment by da2x** [comment]
Just check that the  [`NMConnectivityState` state](https://developer.gnome.org/NetworkManager/1.2/nm-dbus-types.html#NMConnectivityState) is `NM_CONNECTIVITY_FULL`.  This deals with captive portals and everything.

**Comment by zaitcev** [comment]
Surely there must be some kind of resume notification event across the desktop. If that occurs, stop updating for something like 30 seconds.

**Comment by lwindolf** [comment]
@da2x Thanks for the hint on the NetworkManager flag! We need to investigate this.

**Comment by da2x** [comment]
@lwindolf, you’re welcome. There are other useful things in the newer NetworkManager APIs too. E.g. Liferea could check [NMMetered](https://developer.gnome.org/NetworkManager/1.2/nm-dbus-types.html#NMMetered) and disable startup and automatic fetching when on a metered/for-pay network to help people keep bandwidth costs low.

**Comment by poetsmeniet** [comment]
Is anyone working on this? I could investigate further and try a solution or two..

**Comment by lwindolf** [comment]
@poetsmeniet No-one is working on it yet, so if you have time it would be awesome!!!

**Comment by poetsmeniet** [comment]
I took some time to look at the nm docs, to implement an nm dbus check before updating shouldn't be that hard.. I found out:
- Based on org.freedesktop.NetworkManager
- Need at least GLib 2.26
- Does not work with wicd

A more generic approach is also possible, something like a tcp connection check. But that would mean having some kind of server to test the connection on, along with other disadvantages

Please let me know your thoughts. I would prefer to implement the dbus option.

**Comment by da2x** [comment]
> A more generic approach is also possible, something like a tcp connection check. But that would mean having some kind of server to test the connection on, along with other disadvantages

NetworkManager already provides this in `NMConnectivityState` and the various Linux distributions have the required servers and infrastructure setup to provide this functionality by default.

**Comment by poetsmeniet** [comment]
That is clear, but apparently wicd is not covered by network-manager. Shouldn't be a big problem though, I don't think many use it anyway

I was going through net_monitor.c, and noticed that is_nm_connected returns true on states where there would be local and site connectivity only.. Would it not be a solution if it returns true only on state 70? 

Also I can't find any reference to state "3" in the docs?

**Comment by lwindolf** [comment]
As for wicd in the last 10 years to my knowledge there was no single user ticket reporting use of wicd. Always NetworkManager. That being said I have no preference myself on comparing NM vs wicd.

**Comment by rich-coe** [comment]
I'm using neither NM nor wicd.  The 'magic' of discovering whether or not there's a network connection is useless to me.  It used to be a button you could push to go offline/online.   It worked well.

**Comment by lwindolf** [comment]
Nawww... it's just us getting old :-)

**Comment by rich-coe** [comment]
So if I'm running NM what magic has to happen to make it detect the network is up?

**Comment by poetsmeniet** [comment]
I already created a pull request that fixes this issue by checking network manager state to be fully/site connected. [](https://github.com/lwindolf/liferea/pull/689)

**Comment by lwindolf** [comment]
Fixed by merging #689. Everyone please retest!

**Comment by Leiaz** [comment]
Sorry to be late, but this still doesn't work for me. Debian testing, network-manager 1.14.4-4. Liferea still tries to update and all my feeds and shows `HTTP error code 0: Unable to resolve destination host name`.
