### ISSUE TITLE
gnome-keyring issue

### ISSUE THREAD

**Issue by Perflyst** [lwindolf/liferea#672]
I use TinyTinyRSS as source. Since a few days I have to enter my username and password on liferea start.
The error on upstart:
```
** (liferea:8581): CRITICAL **: 19:24:01.844: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 54, in do_query
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'
sys:1: Warning: g_strescape: assertion 'source != NULL' failed
```

Even if I enter them I get `TinyTinyRSS login failed: error 'LOGIN_ERROR'!`

After two trice following appears:
```
** (liferea:7627): CRITICAL **: 19:11:33.802: secret_service_load_collections_sync: assertion 'paths != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 65, in do_store
    coll = self.get_collection()
  File "/usr/lib/liferea/plugins/gnome-keyring.py", line 44, in get_collection
    colls = service.get_collections()
AttributeError: 'NoneType' object has no attribute 'get_collections'
```

I am unable to use Liferea on mulitple machines and I also tried multiple Tiny Tiny RSS installations

**Comment by Perflyst** [comment]
I get this issue with the 1.12.5a compiled by myself and with 1.12.5a from official ubuntu repo.

**Comment by Leiaz** [comment]
I got this error too when testing resetting the "active-plugins" list (the keyring plugin is in the default list). I'm not actually using any service providing "org.freedesktop.secrets" so `service` is None. Maybe the plugin should check for that.

**Comment by lwindolf** [comment]
@Perflyst So a temporary workaround for you could be to start a keyring.

**Comment by Perflyst** [comment]
Yeah I fixed it somehow cant tell you how exactly.

**Comment by lwindolf** [comment]
Closing this for now. If more reports come in let's reconsider.

**Comment by fmagin** [comment]
Note to anyone finding this issue: This message still appears on the terminal if you start liferea (1.12.8-1 in my case) and might be completely unrelated to the issue you are facing. It isn't the reason of the crash I am facing (it appears before I trigger the crash), but it is the only terminal output.

**Comment by lwindolf** [comment]
Today I've experienced some similar error with Ubuntu 26.04. The issue also affected the password manager seahorse which was not able to show keyrings anymore. Error was

    gi.repository.GLib.GError: g-dbus-error-quark: No such secret item at path: /org/freedesktop/secrets/collection/login/24 (19)

with "24" being the id of the former keyring with label 'liferea'.

I found restarting gnome-keyring did solve the issue:

    systemctl --user restart gnome-keyring-daemon.service
