### ISSUE TITLE
[1.12.7] German main and sub-menu entries mixed with English ones in German Linux Mint 19.2 Xfce system

### ISSUE THREAD

**Issue by SingleMalt2104** [lwindolf/liferea#735]
Hello,

thanks for a new bug-fix release of Liferea. I just found a bunch of mixed German/English written main and sub-menu entries which should be sorted out. I am using a German Linux Mint 19.2 Xfce system and installed Liferea version 1.12.7 via this ppa: "ppa:ubuntuhandbook1/apps".

Apart from that all seems fine.

Regards, SingleMalt2104

**Comment by lwindolf** [comment]
Thanks for reporting this. Can you specify which menu entries are affected? Doing a quick check I couldn't find non-translated entries in de_DE.utf8

**Comment by SingleMalt2104** [comment]
The following entries are affected; at least for whatever reason for me:
- main menu entries: - Subscriptions, - Feed, - Item, - Tools, - Search, - Help.
- sub menu entries: - Subscriptions/Update All, - Subscriptions/Mark All As Read, - Subscriptions/New Subscription..., - Subscriptions/New Source, - Subscriptions/Import Feed List..., - Subscriptions/Export Feed List..., - Subscriptions/Quit, - Feed/Mark Items Read, - Feed/Remove All Items, - Feed/Remove, - Item/Next Unread Item, - Item/Previous Item, - Item/Next Item, - Item/Remove, - View/Fullscreen, - View/Normal View, - View/Wide View, - View/Combined View, - View/Reduced Feed List, - Tools/Update Monitor, - Tools/Preferences, - Search/Search All Feeds, - Help/Contents, - Help/Quick Reference, - Help/About.

Above listed entries may be translated in "de_DE.utf8" but are non-translated in my installation. I cannot fathom why. Any suggestions?

Regards, SingleMalt2104

**Comment by lwindolf** [comment]
@SingleMalt2104 Thanks for those details. Can you please provide an output of the `locale` command, when run in your shell?

**Comment by SingleMalt2104** [comment]
@lwindolf Sorry, I downgraded to version 1.12.6 a few days ago and I am on a holiday now.

**Comment by lwindolf** [comment]
No problem. Take your time and let us know if you experience it again!

**Comment by kad09** [comment]
I have same problem with russian localization:
![liferea built from .tar.bz2](https://user-images.githubusercontent.com/39897076/63048546-73206c80-bedf-11e9-8309-293b09638437.png)
That's definitely caused by the fact that bz2 tarball for version 1.12.7 supplied on releases page is somehow different from what is in v1.12.7 git tree. Some linux distributions build their liferea package from it, such as [Arch](https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/liferea&id=3622ed13b70b028aab3fda3e4d39937c3dca197f) (which I use) and ppa mentioned by @SingleMalt2104 . 
String identifiers in po/ru.po are [different](https://gist.github.com/kad09/8cdab97ae3eb49bbba01ac321b20a463) in several places, mostly where `_` is used (e.g. for .tar.bz2 version `Mark All As _Read` is removed, `_Mark All As Read` is added, but version from .tar.bz2 has `_` before "Read" in interface)
However, building from git tag v1.12.7 or github generated .tar.gz is working as expected, at least for russian language. How is that .tar.bz2 generated?

**Comment by lwindolf** [comment]
I always build the tarball with "make dist-bzip2". Must have fuzzied up translation. I'll check this out... 

Thanks for the helpful details!

**Comment by kad09** [comment]
I did some poking around and noticed that you bumped master version to 1.13.0 _before_ tagging the 1.12.7 release. Thus v1.12.7 has 1.13.0 version in configure.ac, and if you change that to 1.12.7, the `dist-bzip2` seems to give correct tarball. I didn't look deeply into make output though.

**Comment by lwindolf** [comment]
Damn... Thanks for the hint!

**Comment by lwindolf** [comment]
@kad09 I've fixed the tag. It is now on the liferea-1_12 branch on the proper commit.

The tarball I've attached with the Github release looks correct to me though. I've must have build it from the correct branch.

**Comment by kad09** [comment]
That didn't fix the problem. I wasn't aware you have branches to support previous release. 

Files in `po/` in `master` and `liferea-1_12` still differ. I don't know why though. But merging `po/` from `master` into `liferea-1_12` (tested `ru.po` and `de.po`) fixes the problem for me. So does that mean po's in `liferea-1_12` became broken at some point? Or I misunderstand something..

**Comment by Erlotinib** [comment]
Hello, the problem still exist with liferea 1.12.8 (french locale fr_FR.utf8)

reverting commit https://github.com/lwindolf/liferea/commit/6872147439ddacfde38e8b3590aac015e041e965 (which comment a bunch of strings at the end of the file) fix the problem.

**Comment by lwindolf** [comment]
@kad09 @Erlotinib Thanks for pointing out that the issue still was not fixed.

It is now fixed by fixing a typo issue inside `POTFILES.in`. The fix is released with 1.12.9 and will be included in 1.13.2
